### ISSUE TITLE
Compatibility issues？

### ISSUE THREAD

**Issue by whes1015** [jpenilla/TabTPS#31] opened 2021-12-07 16:39 UTC
**Describe the bug**
A clear and concise description of what the bug is. Any logs should not be truncated (include the whole log, not just a small portion) and should be uploaded to a paste service like [paste.gg](https://paste.gg)

**To Reproduce**
1. https://github.com/gnembon/fabric-carpet/issues/1205

**Expected behavior**

**Screenshots**

**Server Software and Version:**
 - Vendor: fabric
 - Minecraft Version: 1.18
 - Output of /version command: [e.g. This server is running Paper version git-Paper-53 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)] 

**Additional context**

**Comment by altrisi** [comment] 2021-12-07 21:22
While the version report makes no sense (can't run fabric mods on paper, and mc 1.18 with paper 1.16, what), this is caused by a conflict between carpet fake players and the adventure platform mod, and that is already reported as gnembon/fabric-carpet#1142.

**Comment by jpenilla** [comment] 2021-12-07 23:56
Not a TabTPS issue, this will need to be fixed in adventure-platform or carpet. (hopefully this can be fixed in carpet and we won't need to add workarounds in adventure, as carpet is the mod responsible for creating and adding fake players which don't behave as expected compared to vanilla players (null channel))

**Closed by jpenilla** 2021-12-07 23:56 UTC
Labels: bug
