### ISSUE TITLE
Not sure if TabTPS is ignoring "Async tasks"

### ISSUE THREAD

**Issue by pahanakun** [jpenilla/TabTPS#35] opened 2022-01-17 03:05 UTC
I'm getting two very different numbers when trying to get information on MSPT
When using "/tick health" from carpet, its showing an average tick time of 31.383ms (to be expected, chunky is currently pregenerating chunks). When using "/mspt" its showing averages from about 5.5ms to 6ms, which seem awfully low for running chunky.

The majority of the tick time is coming from "async tasks" (25.400ms) and when that is removed from carpet's breakdown of average MSPT, you get approximately TabTPS's average tick time.

This isn't really an issue, maybe not even a bug, but I wanted to point this out in case it might help make TabTPS more accurate.

**Comment by jpenilla** [comment] 2022-01-17 08:27
The way the carpet tick health command presents the sum of async tasks and the server tick as "Average tick time" doesn't make much sense to me... the numbers from TabTPS line up with carpets MSPT logging with `/log tps`, and also align with what is reported by spark. Closing as works as intended

**Closed by jpenilla** 2022-01-17 08:27 UTC
Labels: invalid
