### ISSUE TITLE
[Feature Request] 1.19 Compatibility

### ISSUE THREAD

**Issue by SavageTheUnicorn** [jpenilla/TabTPS#41] opened 2022-06-14 21:38 UTC
1.19 support. I love this plugin and it's an absolute necessity for me and I just upgraded to 1.19. Please add compatibility!

**Comment by jpenilla** [comment] 2022-06-14 22:38
duplicate of #40

the issue tracker is not a support forum, the discord is a better place to ask questions. the jenkins channel in the discord is also where you can find dev builds

**Closed** 2022-06-14 22:38 UTC
Labels: enhancement
